### ISSUE TITLE
Glossary entries are not used when content is translated - because of bug in DataHandlerHook, glossary entries are not synced

### ISSUE THREAD

**Issue by sypets** [web-vision/wv_deepltranslate#99]
**Update**: The problem could be tracked down, see comments below, see PR #100.

-------

In general, it would be nice if there were a status check or one would get some feedback if the glossary is being used.

Is there something I can do to troubleshoot this or is something missing? Is further configuration necessary?

Entries "DeepL Glossaries Sync" are not automatically created (our contact in another university gave this tip, that this should happen).

In the (logging framework) logs there is no error during the timeframe where the entries were created or translations took place. 

## Reproduce 

Followed information in README: https://github.com/web-vision/wv_deepltranslate#deepl-glossary 

1. Created page A for translation with default language = German and translation (sys_language_uid=1) English
2. Created subpage B for glossary entries, selected in page properties tab "Behaviour" | "Use as Container" | "Contains Plugin": **"Deepl Glossar"**
3. Switched to list module and added glossary entries:
    - de: Fakultät, en: "school"
    - de: Semesterferien, en "lecture-free period"

![image](https://user-images.githubusercontent.com/13206455/212324098-7a7bca2d-ac2c-4457-bd96-5147d83804d6.png)

 4. On page A, translated existing text to English using "**Translate (deepl)**" (not "Translate (deepl) (autodeted)")

![image](https://user-images.githubusercontent.com/13206455/212324644-04bdcc92-0de2-45b4-b0f9-a71addb100d7.png)

> Für die **Fakultät** gibt es keine Studiengänge.
> Momentan haben wir **Semesterferien**.

The result is:
> There are no courses of study for the **faculty**.
> At the moment we have **semester break**.

I would expect school instead of faculty and "lecture-free period" instead of "semester break"

## version

* current master wv_deepltranslate
* PHP 7.4
* TYPO3 11.5.21

or

* current master wv_deepltranslate
* PHP 8.1
* TYPO3 11.5.22

because of #98 the code was patched:

```
git diff
diff --git a/Classes/Hooks/DataHandlerHook.php b/Classes/Hooks/DataHandlerHook.php
index 64bb139..880fea0 100644
--- a/Classes/Hooks/DataHandlerHook.php
+++ b/Classes/Hooks/DataHandlerHook.php
@@ -95,7 +95,7 @@ class DataHandlerHook implements LoggerAwareInterface
         if ($status !== 'update') {
             return;
         }
-        if ($fieldArray['l10n_parent'] === 0) {
+         $l10n_parent = $fieldArray['l10n_parent'] ?? false;
+        if ($l10n_parent === 0) {
             return;
         }

```

## Settings

I can't show you my API key, but the rest is:

![image](https://user-images.githubusercontent.com/13206455/212325052-af135649-82fd-4758-8ca5-19134581118d.png)

![image](https://user-images.githubusercontent.com/13206455/212325139-b353f35a-4cac-4aca-bd17-2071ce525523.png)

![image](https://user-images.githubusercontent.com/13206455/212325302-2ac16261-9abb-4a86-8904-d3f7f364f205.png)

site configuration:

```
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    languageId: 1
    base: /en/
    typo3Language: default
    locale: en_UK.UTF8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-GB
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: gb
    websiteTitle: 'University of Oldenburg'


```
